---
apiVersion: v1
kind: Secret
metadata:
  name: echo-app-secret
  namespace: echo-app
type: Opaque
stringData:
  DATABASE_URL: "DATABASE_URL_PLACEHOLDER"
  REDIS_URL: "REDIS_URL_PLACEHOLDER"
  RABBITMQ_URL: "RABBITMQ_URL_PLACEHOLDER"
